# Generated by Django 4.0 on 2022-01-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_key_pair'),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypair',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
