# Generated by Django 4.0 on 2022-01-08 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 1, 8, 11, 40, 29, 683173, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
