# Generated by Django 4.0 on 2022-01-12 10:26

from django.db import migrations, models
from django.db.models import Q


def populate_data(apps, _):
    Id = apps.get_model("ids", "Id")
    ids = []
    for obj in Id.objects.filter(Q(id_name="") | Q(issuer_name="")):
        obj.issuer_name = obj.verifiable_id["issuer"]["name"]
        obj.id_name = obj.verifiable_id["idName"]
        ids.append(obj)

    Id.objects.bulk_update(ids, ["issuer_name", "id_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("ids", "0003_alter_id_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="id",
            name="id_name",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="id",
            name="issuer_name",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(populate_data),
    ]
