# Generated by Django 4.0 on 2022-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0004_id_id_name_id_issuer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='type',
            field=models.CharField(max_length=34),
        ),
    ]
