# Generated by Django 4.0 on 2022-01-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_pair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='keys.keypair'),
        ),
    ]
